# -*- mode: ruby -*-
# vi: set ft=ruby :

$domain_name = ".company.com"
$base_segment = "172.25.74."
$public_network_interface = "wlp3s0"

http_repository = "http://repo.company.com:9080/domino/"
install_file = "DOM_SVR_V10.0.1_64_BIT_Lnx.tar"

configure_etc_hosts = <<SCRIPT
cat > /etc/hosts <<EOF
127.0.0.1           localhost localhost.localdomain
#{$base_segment}1   repo.company.com              # HTTP repository for files
#{$base_segment}101 srv101 srv101.company.com     # Nginx
#{$base_segment}102 srv102 srv102.company.com     # Domino 1
#{$base_segment}103 srv103 srv103.company.com     # Domino 2
EOF
SCRIPT

configure_os_settings = <<SCRIPT
echo "net.ipv6.conf.all.disable_ipv6 = 1" | sudo tee --append /etc/sysctl.conf > /dev/null
echo "net.ipv6.conf.default.disable_ipv6 = 1" | sudo tee --append /etc/sysctl.conf > /dev/null
echo "* soft nofile 1048576" | sudo tee --append /etc/security/limits.conf > /dev/null
echo "* hard nofile 1048576" | sudo tee --append /etc/security/limits.conf > /dev/null
echo "root soft nofile 1048576" | sudo tee --append /etc/security/limits.conf > /dev/null
echo "root hard nofile 1048576" | sudo tee --append /etc/security/limits.conf > /dev/null
sudo sysctl -p
echo "disable selinux"
sudo setenforce 0
sudo sed -i 's/=enforcing/=disabled/g' /etc/selinux/config
SCRIPT

install_os_required_packages = <<SCRIPT
sudo yum update
sudo yum install -y wget curl net-tools ntp bc perl
# enable ntp to sync time
echo 'sync time'
sudo systemctl start ntpd
sudo systemctl enable ntpd
SCRIPT

create_notes_users = <<SCRIPT
mkdir -p /domino
groupadd notes
useradd notes -m -g notes -d /domino/notesdata
chown -R notes.notes /domino
SCRIPT

generate_domino_response_file = <<SCRIPT
cat > /opt/IBM/Binaries/domino10.rsp <<EOF
-G licenseAccepted=true
-W InstallDataOnlyOptionPanel.InstallDataOnly=false
-P installLocation="/opt/ibm/domino"
-W normalData.installLocationData="/domino/notesdata"
-W NameUserGroupPanel.UserName="notes"
-W NameUserGroupPanel.GroupName="notes"
-W SetupTypePanel.selectedSetupTypeId=EnterpriseServer
-W ServerSetupPanel.ServerSetupType="Manual"
-P LicenseFeature.active=true
-P ProgramFilesFeature.active=true
-P BillingSupportFeature.active=true
-P ClusteringSupportFeature.active=true
-P bean2236.active=true
-P DataFilesFeature.active=true
-P beanRequiredTemplates.active=true
-P beanAdministrationTemplates.active=true
-P beanOptionalTemplates.active=true
-P beanCertificateManagement.active=true
-P beanWebServicesDataFiles.active=true
-P beanReadme.active=true
-P beanDojo.active=true
-P beanDojo2.active=true
-P beanXSPages.active=true
-P DECSFeature.active=true
-P DOLSFeature.active=false
-P DWAFeature.active=true
-P SametimeIntegrationFeature.active=true
-P RMEFeature.active=true
-P HelpFeature.active=true
-P OSIntegFeature.active=true
EOF
SCRIPT

install_domino = <<SCRIPT
mkdir -p /opt/IBM/Binaries
cd /opt/IBM/Binaries
wget #{ http_repository }#{ install_file }
tar -xf #{ install_file }
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
/bin/bash -c "/opt/IBM/Binaries/linux64/domino/install -silent -options /opt/IBM/Binaries/domino10.rsp"
SCRIPT


Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"

    config.vm.define "domino" do |node|
        node.vm.hostname = "srv102" + $domain_name
        $ip = $base_segment + "102"
        node.vm.network "private_network", ip: $ip
        node.vm.network "public_network", bridge: $public_network_interface, auto_config: true
        #node.vm.synced_folder "/Users/DuffQiu/share", "/home/vagrant/share"

        node.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 1
            vb.name = "deploy-domino-vagrant"

            #unless File.exist?("#{sharedarea_storage_disk}")
            #    vb.customize ['createmedium', 'disk', '--filename', "#{sharedarea_storage_disk}", '--format', 'VMDK', '--size', 50 * 1024]
            #end
            #vb.customize ['storagectl', :id, '--name', 'SATA', '--add', 'sata', '--hostiocache', 'on'] # use host I/O cache
            #vb.customize ['storageattach', :id, '--storagectl', 'SATA', '--port', 0, '--device', 0, '--type', 'hdd', '--nonrotational', 'on', '--medium', "#{sharedarea_storage_disk}"]

            vb.customize ["modifyvm", :id, "--audio", "none"] # turn audio off
            vb.customize ["modifyvm", :id, "--clipboard", "disabled"] # disable clipboard
        end
    end

    #config.vm.synced_folder ".", "/vagrant", disabled: true
    config.ssh.forward_agent = true
    config.ssh.forward_x11 = true
    config.ssh.insert_key = false
    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    #
    #
    config.vm.provision "shell", privileged: true, inline: configure_etc_hosts, keep_color: true, name: "configure_etc_hosts"
    config.vm.provision "shell", privileged: true, inline: configure_os_settings, keep_color: true, name: "configure_os_settings"
    config.vm.provision "shell", privileged: true, inline: install_os_required_packages, keep_color: true, name: "install_os_required_packages"
    config.vm.provision "shell", privileged: true, inline: create_notes_users, keep_color: true, name: "create_notes_users"
    config.vm.provision "shell", privileged: true, inline: generate_domino_response_file, keep_color: true, name: "generate_domino_response_file"
    config.vm.provision "shell", privileged: true, inline: install_domino, keep_color: true, name: "install_domino"

end
