# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define "web" do |webvm|
        webvm.vm.box = "hashicorp-vagrant/centos-7.4"
        webvm.vm.network :private_network, ip: "192.168.33.10 "
        webvm.vm.provision "ansible" do |ansible|
            ansible.playbook = "webserver.yml"
            ansible.verbose = "vvv"
            ansible.groups = {
                "webserver" => ["192.168.33.10 "],
                "dbserver" => ["192.168.33.11 "],
            }
            ansible.limit = "webserver"
        end
    end

    config.vm.define "db" do |dbvm|
        dbvm.vm.box = "hashicorp-vagrant/centos-7.4"
        dbvm.vm.network :private_network, ip: "192.168.33.11 "
        dbvm.vm.provision "ansible" do |ansible|
            ansible.playbook = "dbserver.yml"
            ansible.verbose = "vvv"
            ansible.groups = {
                "webserver" => ["192.168.33.10 "],
                "dbserver" => ["192.168.33.11 "],
            }
            ansible.limit = "dbserver"
        end
    end

    config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", "1024"]
    end
end