# -*- mode: ruby -*-
# vi: set ft=ruby :

$domain_name = ".company.com"
$base_segment = "172.25.74."
$public_network_interface = "wlp3s0"

http_repository = "http://repo.company.com:9080/db2/"
install_file = "DB2_ESE_AUSI_Svr_11.1_Linux_86-64.tar.gz"

#dasusr1_password = "linux1"
#db2inst1_password = "linux1"
#db2fenc1_password = "linux1"
#lcuser_password = "linux1"

configure_etc_hosts = <<SCRIPT
cat > /etc/hosts <<EOF
127.0.0.1           localhost localhost.localdomain
#{$base_segment}1   repo.company.com              # HTTP repository for files
#{$base_segment}101 srv101 srv101.company.com     # DMGR, SharedArea, LDAP Server
#{$base_segment}102 srv102 srv102.company.com     # WAS for Connections
#{$base_segment}103 srv103 srv103.company.com     # WAS for Forms/Viewer/Conversion
#{$base_segment}104 srv104 srv104.company.com     # DB2
EOF
SCRIPT

configure_os_settings = <<SCRIPT
echo "net.ipv6.conf.all.disable_ipv6 = 1" | sudo tee --append /etc/sysctl.conf > /dev/null
echo "net.ipv6.conf.default.disable_ipv6 = 1" | sudo tee --append /etc/sysctl.conf > /dev/null
echo "* soft nofile 1048576" | sudo tee --append /etc/security/limits.conf > /dev/null
echo "* hard nofile 1048576" | sudo tee --append /etc/security/limits.conf > /dev/null
echo "root soft nofile 1048576" | sudo tee --append /etc/security/limits.conf > /dev/null
echo "root hard nofile 1048576" | sudo tee --append /etc/security/limits.conf > /dev/null
sudo sysctl -p
echo "disable selinux"
sudo setenforce 0
sudo sed -i 's/=enforcing/=disabled/g' /etc/selinux/config
SCRIPT


Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"

    config.vm.define "db2-server" do |node|
        node.vm.hostname = "srv104" + $domain_name
        $ip = $base_segment + "104"
        node.vm.network "private_network", ip: $ip
        node.vm.network "public_network", bridge: $public_network_interface, auto_config: true
        #node.vm.synced_folder "/Users/DuffQiu/share", "/home/vagrant/share"

        node.vm.provider "virtualbox" do |vb|
            vb.memory = "4096"
            vb.cpus = 1
            vb.name = "deploy-db2-vagrant-ansible"

            #unless File.exist?("#{sharedarea_storage_disk}")
            #    vb.customize ['createmedium', 'disk', '--filename', "#{sharedarea_storage_disk}", '--format', 'VMDK', '--size', 50 * 1024]
            #end
            #vb.customize ['storagectl', :id, '--name', 'SATA', '--add', 'sata', '--hostiocache', 'on'] # use host I/O cache
            #vb.customize ['storageattach', :id, '--storagectl', 'SATA', '--port', 0, '--device', 0, '--type', 'hdd', '--nonrotational', 'on', '--medium', "#{sharedarea_storage_disk}"]

            vb.customize ["modifyvm", :id, "--audio", "none"] # turn audio off
            vb.customize ["modifyvm", :id, "--clipboard", "disabled"] # disable clipboard
        end
    end

    #config.vm.synced_folder ".", "/vagrant", disabled: true
    config.ssh.forward_agent = true
    config.ssh.forward_x11 = true
    config.ssh.insert_key = false
    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    #
    config.vm.provision "shell", privileged: true, inline: configure_etc_hosts, keep_color: true, name: "configure_etc_hosts"
    config.vm.provision "shell", privileged: true, inline: configure_os_settings, keep_color: true, name: "configure_os_settings"
    #
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/db2server.yml"
        ansible.verbose = "vvv"
     end
end
