# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp-vagrant/centos-7.4"

  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.hostname = "webserver2"
  config.vm.define "webserver"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
     yum -y update
     yum -y install httpd
  SHELL
end