---
- name:        "Configure Instance db2inst1"
  command:
    chdir=/opt/ibm/db2/V11.1/instance/
    ./db2icrt -u db2fenc1 db2inst1
  register:      cout
  #changed_when:  ( cout.stdout.find(__version_check) != -1)

- name:        "Configure /etc/services"
  shell: |
    sed -i 's/db2c_db2inst1/#db2c_db2inst1/g' /etc/services
    sed -i 's/DB2_db2inst1/#DB2_db2inst1/g' /etc/services
    echo "DB2_db2inst1      50000/tcp" |sudo tee --append /etc/services
    echo "DB2_db2inst1_1    50001/tcp" |sudo tee --append /etc/services
    echo "DB2_db2inst1_2    50002/tcp" |sudo tee --append /etc/services
    echo "DB2_db2inst1_3    50003/tcp" |sudo tee --append /etc/services
    echo "DB2_db2inst1_4    50004/tcp" |sudo tee --append /etc/services
    echo "DB2_db2inst1_END  50005/tcp" |sudo tee --append /etc/services
  register:      cout

- name:        "Start IBM DB2 Server"
  command:     "su - db2inst1 -c 'db2start'"
  register:      cout
  changed_when:  ( cout.stdout.find("DB2START processing was succesful") != -1)

# create_db2icrt_and_start = <<SCRIPT
# cd /opt/ibm/db2/V11.1/instance/
# ./db2icrt -u db2fenc1 db2inst1
# sed -i 's/db2c_db2inst1/#db2c_db2inst1/g' /etc/services
# sed -i 's/DB2_db2inst1/#DB2_db2inst1/g' /etc/services
# echo "DB2_db2inst1      50000/tcp" |sudo tee --append /etc/services
# echo "DB2_db2inst1_1    50001/tcp" |sudo tee --append /etc/services
# echo "DB2_db2inst1_2    50002/tcp" |sudo tee --append /etc/services
# echo "DB2_db2inst1_3    50003/tcp" |sudo tee --append /etc/services
# echo "DB2_db2inst1_4    50004/tcp" |sudo tee --append /etc/services
# echo "DB2_db2inst1_END  50005/tcp" |sudo tee --append /etc/services
# su - db2inst1 -c 'db2start'
# SCRIPT
